# Generated by Django 3.1.6 on 2026-09-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210530_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='doctorID',
            field=models.ForeignKey(db_column='doctorID', on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule_doctorID', to='reservations.doctor'),
        ),
    ]
